-file("/usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/parsetools-2.1.2/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(macro_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 62).

unquote([$'|Cs]) -> unquote(Cs, []);
unquote([$"|Cs]) -> unquote(Cs, []);
unquote([$`|Cs]) -> unquote(Cs, []).

unquote([$"], Acc)         -> lists:reverse(Acc);
unquote([$'], Acc)         -> lists:reverse(Acc);
unquote([$`], Acc)         -> lists:reverse(Acc);
unquote([$\\,$0|Cs], Acc)  -> unquote(Cs, [0|Acc]);
unquote([$\\,$a|Cs], Acc)  -> unquote(Cs, [7|Acc]);
unquote([$\\,$b|Cs], Acc)  -> unquote(Cs, [8|Acc]);
unquote([$\\,$f|Cs], Acc)  -> unquote(Cs, [12|Acc]);
unquote([$\\,$n|Cs], Acc)  -> unquote(Cs, [10|Acc]);
unquote([$\\,$r|Cs], Acc)  -> unquote(Cs, [13|Acc]);
unquote([$\\,$t|Cs], Acc)  -> unquote(Cs, [9|Acc]);
unquote([$\\,$v|Cs], Acc)  -> unquote(Cs, [11|Acc]);
unquote([$\\,$"|Cs], Acc)  -> unquote(Cs, [$"|Acc]);
unquote([$\\,$'|Cs], Acc)  -> unquote(Cs, [$'|Acc]);
unquote([$\\,$\\|Cs], Acc) -> unquote(Cs, [$\\|Acc]);
unquote([$\\,$&|Cs], Acc)  -> unquote(Cs, Acc);	%% stop escape
unquote([$\\,D|Cs], Acc) when D >= $0, D =< $9 -> unquote_char(Cs, D -$0, Acc);
unquote([$\\,$x|Cs], Acc)  -> unquote_hex(Cs, 0, Acc);
unquote([C|Cs], Acc)       -> unquote(Cs, [C|Acc]).

unquote_char([D|Cs], N, Acc) when D >= $0, D =< $9 -> unquote_char(Cs, N *10 +D -$0, Acc);
unquote_char(Cs, N, Acc)   -> unquote(Cs, [N|Acc]).

unquote_hex([H|Cs], N, Acc) when H >= $0, H =< $9 -> unquote_hex(Cs, N *16 +H -$0, Acc);
unquote_hex([H|Cs], N, Acc) when H >= $a, H =< $f -> unquote_hex(Cs, N *16 +H -$a +10, Acc);
unquote_hex([H|Cs], N, Acc) when H >= $A, H =< $F -> unquote_hex(Cs, N *16 +H -$A +10, Acc);
unquote_hex(Cs, N, Acc)    -> unquote(Cs, [N|Acc]).

-file("/usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/parsetools-2.1.2/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.erl", 315).
yystate() -> 63.

yystate(70, [111|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [101|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 110 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,70};
yystate(69, [116|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,69};
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [62|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [45|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,68};
yystate(67, [45|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 13, Tlen);
yystate(67, [10|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line+1, Tlen+1, 13, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(67, Ics, Line, Tlen+1, 13, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(67, Ics, Line, Tlen+1, 13, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,67};
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(66, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,66};
yystate(65, [101|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,65};
yystate(64, [99|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [97|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [98|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,64};
yystate(63, [8704|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [8594|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [955|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [125|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [124|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [123|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [116|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [115|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [114|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [113|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [112|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [111|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [110|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [109|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [108|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [106|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [107|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [105|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [100|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [99|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [97|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [98|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [96|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [94|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [93|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [92|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [91|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [63|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [64|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [62|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [61|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [60|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [59|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [58|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [47|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [46|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [45|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [44|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [42|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [43|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [40|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [41|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [39|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [35|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [34|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [33|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [10|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line+1, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(67, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(67, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 38 ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(66, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 104 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 126, C =< 944 ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 1024, C =< 8207 ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 8602, C =< 8703 ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 9728 ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,63};
yystate(62, [114|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,62};
yystate(61, [110|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,61};
yystate(60, [101|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [97|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,60};
yystate(59, [45|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 13, Tlen);
yystate(59, [10|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line+1, Tlen+1, 13, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(59, Ics, Line, Tlen+1, 13, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(59, Ics, Line, Tlen+1, 13, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 44 ->
    yystate(59, Ics, Line, Tlen+1, 13, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 46 ->
    yystate(59, Ics, Line, Tlen+1, 13, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,59};
yystate(58, [61|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 4, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,58};
yystate(57, [119|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 118 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 120, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,57};
yystate(56, [8594|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [955|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [96|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [46|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [47|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [45|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [10|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 44 ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 944 ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 1024, C =< 8207 ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 8602, C =< 8704 ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 9728 ->
    yystate(59, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,56};
yystate(55, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(54, [47|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 10, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,54};
yystate(53, [111|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [101|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [97|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 110 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,53};
yystate(52, [100|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,52};
yystate(51, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 0, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,50};
yystate(49, [101|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,49};
yystate(48, [110|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,48};
yystate(47, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 1, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,46};
yystate(45, [102|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(43, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(42, [105|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,42};
yystate(41, [102|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,41};
yystate(40, [110|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,40};
yystate(39, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(38, [101|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,38};
yystate(37, [105|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [97|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 104 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,37};
yystate(36, [92|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 14, Tlen);
yystate(36, [39|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 14, Tlen);
yystate(36, [10|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line+1, Tlen+1, 14, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Tlen+1, 14, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(4, Ics, Line, Tlen+1, 14, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(4, Ics, Line, Tlen+1, 14, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(4, Ics, Line, Tlen+1, 14, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,36};
yystate(35, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line+1, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [118|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 117 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 119, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,34};
yystate(33, [100|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,33};
yystate(32, [119|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 118 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 120, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,32};
yystate(31, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(30, [115|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,30};
yystate(29, [110|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,29};
yystate(28, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line+1, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(26, [97|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,26};
yystate(25, [101|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,25};
yystate(24, [97|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,24};
yystate(23, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(22, [105|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,22};
yystate(21, [101|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,21};
yystate(20, [92|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 12, Tlen);
yystate(20, [39|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 12, Tlen);
yystate(20, [10|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line+1, Tlen+1, 12, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Tlen+1, 12, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(4, Ics, Line, Tlen+1, 12, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(4, Ics, Line, Tlen+1, 12, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(4, Ics, Line, Tlen+1, 12, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,20};
yystate(19, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 11, Tlen);
yystate(19, [34|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 11, Tlen);
yystate(19, [10|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line+1, Tlen+1, 11, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(35, Ics, Line, Tlen+1, 11, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(35, Ics, Line, Tlen+1, 11, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(35, Ics, Line, Tlen+1, 11, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(35, Ics, Line, Tlen+1, 11, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,19};
yystate(18, [97|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,18};
yystate(17, [107|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 106 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 108, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,17};
yystate(16, [112|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [101|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 111 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,16};
yystate(15, [114|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,15};
yystate(14, [115|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,14};
yystate(13, [117|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(11, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line+1, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, [116|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,10};
yystate(9, [99|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [97|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [98|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,9};
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,8};
yystate(7, [122|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [121|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 120 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,7};
yystate(6, [101|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,6};
yystate(5, [108|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,5};
yystate(4, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line+1, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,4};
yystate(3, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 14, Tlen);
yystate(3, [34|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 14, Tlen);
yystate(3, [10|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line+1, Tlen+1, 14, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(35, Ics, Line, Tlen+1, 14, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(35, Ics, Line, Tlen+1, 14, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(35, Ics, Line, Tlen+1, 14, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(35, Ics, Line, Tlen+1, 14, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,3};
yystate(2, [116|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,2};
yystate(1, [97|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,1};
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 8705, C =< 9727 ->
    yystate(8, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, _, _, _) ->
    yyaction_13();
yyaction(14, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 40).
yyaction_0(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_1/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 41).
yyaction_1(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_2/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 42).
yyaction_2(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_3/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 43).
yyaction_3(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_4/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 44).
yyaction_4(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_5/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 45).
yyaction_5(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_6/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 47).
yyaction_6(TokenChars, TokenLine) ->
     { token, { token_digits, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_7/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 48).
yyaction_7(TokenChars, TokenLine) ->
     { token, { token_id, TokenLine, TokenChars } } .

-compile({inline,yyaction_8/1}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 49).
yyaction_8(TokenLine) ->
     { token, { token_arrow, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 50).
yyaction_9(TokenLine) ->
     { token, { token_forall, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 51).
yyaction_10(TokenLine) ->
     { token, { token_lambda, TokenLine } } .

-compile({inline,yyaction_11/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 54).
yyaction_11(TokenChars, TokenLine) ->
     { token, { token_quoted_literal, TokenLine, unquote (TokenChars) } } .

-compile({inline,yyaction_12/2}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 55).
yyaction_12(TokenChars, TokenLine) ->
     { token, { token_atom, TokenLine, unquote (TokenChars) } } .

-compile({inline,yyaction_13/0}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 57).
yyaction_13() ->
     skip_token .

-compile({inline,yyaction_14/1}).
-file("/Users/5HT/depot/groupoid/exe/src/macro_lexer.xrl", 58).
yyaction_14(TokenChars) ->
     { error, TokenChars } .

-file("/usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/parsetools-2.1.2/include/leexinc.hrl", 290).
